"""Tracker schema: companies, jobs, applications, event timeline, contacts

Tenancy model — worth reading before changing anything here.

  Tenant-scoped (RLS enforced):  applications, application_events,
                                 interview_stages, contacts
  Shared reference (no RLS):     companies, jobs, job_requirements, job_skills,
                                 skills

The split follows what is actually private. A job description is something the
employer published to the world; it is not yours. What *is* yours is that you
applied, when, and what happened next — and every one of those lives on a
tenant-scoped table. Sharing job rows is also what makes deduplication and the
Phase 5 cross-company analytics possible at all; a per-user copy of every
posting would fragment both.

Accepted trade-off: a second user could in principle edit a shared job row.
``jobs.created_by_user_id`` records the author so writes can be narrowed to the
creator with a policy-only migration if that ever matters. The API additionally
never exposes a bare job list — jobs are reachable only through an application
you own.

Revision ID: 0002_tracker_schema
Revises: 0001_initial_users
Create Date: 2026-08-30
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.rls import disable_user_isolation, enable_user_isolation, grant_shared_table
from app.domain.enums import (
    ApplicationStatus,
    EmploymentType,
    EventSource,
    EventType,
    InterviewStageType,
    Priority,
    RequirementKind,
    SalaryPeriod,
    Seniority,
    StageOutcome,
    WorkMode,
    check_constraint,
)
from app.domain.seed_skills import SEED_SKILLS

revision: str = "0002_tracker_schema"
down_revision: str | None = "0001_initial_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = ["applications", "application_events", "interview_stages", "contacts"]
SHARED_WRITABLE = ["companies", "jobs", "job_requirements", "job_skills"]

# (table, column, enum, nullable) — kept as data so the constraint list and the
# Python enums cannot drift apart silently.
ENUM_CONSTRAINTS = [
    ("applications", "current_status", ApplicationStatus, False),
    ("applications", "priority", Priority, False),
    ("application_events", "event_type", EventType, False),
    ("application_events", "source", EventSource, False),
    ("interview_stages", "stage_type", InterviewStageType, False),
    ("interview_stages", "outcome", StageOutcome, False),
    ("jobs", "work_mode", WorkMode, True),
    ("jobs", "employment_type", EmploymentType, True),
    ("jobs", "seniority", Seniority, True),
    ("jobs", "salary_period", SalaryPeriod, True),
    ("job_requirements", "kind", RequirementKind, False),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("size", sa.String(length=60), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_domain"), "companies", ["domain"], unique=False)
    op.create_index(
        op.f("ix_companies_normalized_name"), "companies", ["normalized_name"], unique=True
    )
    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column(
            "aliases", postgresql.ARRAY(sa.String(length=120)), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    op.create_index(op.f("ix_skills_category"), "skills", ["category"], unique=False)
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=True)
    op.create_table(
        "jobs",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("seniority", sa.String(length=30), nullable=True),
        sa.Column("employment_type", sa.String(length=30), nullable=True),
        sa.Column("work_mode", sa.String(length=20), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("source_platform", sa.String(length=60), nullable=True),
        sa.Column("posted_at", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("responsibilities", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("salary_period", sa.String(length=10), nullable=True),
        sa.Column("years_experience_min", sa.Integer(), nullable=True),
        sa.Column("years_experience_max", sa.Integer(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("extraction_model", sa.String(length=80), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_jobs_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_jobs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_company_id"), "jobs", ["company_id"], unique=False)
    op.create_index(op.f("ix_jobs_content_hash"), "jobs", ["content_hash"], unique=False)
    op.create_index(
        op.f("ix_jobs_created_by_user_id"), "jobs", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_jobs_source_platform"), "jobs", ["source_platform"], unique=False)
    op.create_index(op.f("ix_jobs_work_mode"), "jobs", ["work_mode"], unique=False)
    op.create_table(
        "applications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=True),
        sa.Column("current_status", sa.String(length=20), nullable=False),
        sa.Column(
            "current_status_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("job_score", sa.Integer(), nullable=True),
        sa.Column("match_score", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_applications_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_applications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("user_id", "job_id", name="uq_applications_user_id_job_id"),
    )
    op.create_index(
        op.f("ix_applications_current_status"), "applications", ["current_status"], unique=False
    )
    op.create_index(op.f("ix_applications_job_id"), "applications", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_applications_last_activity_at"), "applications", ["last_activity_at"], unique=False
    )
    op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False)
    op.create_index(
        "ix_applications_user_status_activity",
        "applications",
        ["user_id", "current_status", "last_activity_at"],
        unique=False,
    )
    op.create_table(
        "job_requirements",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_requirements_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirements")),
    )
    op.create_index(
        op.f("ix_job_requirements_job_id"), "job_requirements", ["job_id"], unique=False
    )
    op.create_table(
        "job_skills",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("years_required", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_skills_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_job_skills_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", "skill_id", name=op.f("pk_job_skills")),
        sa.UniqueConstraint("job_id", "skill_id", name="uq_job_skills_job_id_skill_id"),
    )
    op.create_table(
        "application_events",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_events_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_application_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_events")),
    )
    op.create_index(
        "ix_application_events_application_occurred",
        "application_events",
        ["application_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_events_event_type"), "application_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_application_events_source"), "application_events", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_application_events_user_id"), "application_events", ["user_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_contacts_application_id_applications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_contacts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(
        op.f("ix_contacts_application_id"), "contacts", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_index(op.f("ix_contacts_user_id"), "contacts", ["user_id"], unique=False)
    op.create_table(
        "interview_stages",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("stage_type", sa.String(length=30), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=15), nullable=False),
        sa.Column("interviewer", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_interview_stages_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_interview_stages_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_stages")),
        sa.UniqueConstraint("application_id", "round_number", name="uq_interview_stages_app_round"),
    )
    op.create_index(
        op.f("ix_interview_stages_application_id"),
        "interview_stages",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_stages_user_id"), "interview_stages", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # --- Enum CHECK constraints ---------------------------------------------
    # varchar + CHECK rather than native enums: this vocabulary is known to grow
    # (Phase 4 adds follow-up events), and widening a CHECK is reversible where
    # ALTER TYPE ADD VALUE is not. See app/domain/enums.py.
    for table, column, enum_cls, nullable in ENUM_CONSTRAINTS:
        predicate = f"{column} {check_constraint(enum_cls)}"
        if nullable:
            predicate = f"{column} IS NULL OR {predicate}"
        op.create_check_constraint(f"{column}_valid", table, predicate)

    # Salary sanity. A max below a min is always an extraction bug, and Phase 2
    # will be writing these from an LLM — better to reject than to store.
    op.create_check_constraint(
        "salary_range_ordered",
        "jobs",
        "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
    )
    op.create_check_constraint(
        "years_range_ordered",
        "jobs",
        "years_experience_min IS NULL OR years_experience_max IS NULL "
        "OR years_experience_min <= years_experience_max",
    )
    op.create_check_constraint("round_number_positive", "interview_stages", "round_number >= 1")

    # --- Row Level Security --------------------------------------------------
    for table in TENANT_TABLES:
        for statement in enable_user_isolation(table):
            op.execute(statement)

    for table in SHARED_WRITABLE:
        for statement in grant_shared_table(table):
            op.execute(statement)

    # skills is SELECT-only for the runtime role: the taxonomy is curated, and
    # Phase 2 normalises onto it rather than inventing entries. When Phase 2
    # adds a reviewed-insert path it can widen this grant then.
    op.execute("GRANT SELECT ON skills TO app_user")

    # --- Seed the skill taxonomy --------------------------------------------
    op.bulk_insert(
        sa.table(
            "skills",
            sa.column("name", sa.String),
            sa.column("slug", sa.String),
            sa.column("category", sa.String),
            sa.column("aliases", postgresql.ARRAY(sa.String)),
        ),
        [
            {"name": s.name, "slug": s.slug, "category": s.category, "aliases": s.aliases}
            for s in SEED_SKILLS
        ],
    )


def downgrade() -> None:
    for table in TENANT_TABLES:
        for statement in disable_user_isolation(table):
            op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_stages_user_id"), table_name="interview_stages")
    op.drop_index(op.f("ix_interview_stages_application_id"), table_name="interview_stages")
    op.drop_table("interview_stages")
    op.drop_index(op.f("ix_contacts_user_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_application_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_application_events_user_id"), table_name="application_events")
    op.drop_index(op.f("ix_application_events_source"), table_name="application_events")
    op.drop_index(op.f("ix_application_events_event_type"), table_name="application_events")
    op.drop_index("ix_application_events_application_occurred", table_name="application_events")
    op.drop_table("application_events")
    op.drop_table("job_skills")
    op.drop_index(op.f("ix_job_requirements_job_id"), table_name="job_requirements")
    op.drop_table("job_requirements")
    op.drop_index("ix_applications_user_status_activity", table_name="applications")
    op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_last_activity_at"), table_name="applications")
    op.drop_index(op.f("ix_applications_job_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_current_status"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_jobs_work_mode"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_source_platform"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_by_user_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_content_hash"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_company_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_index(op.f("ix_skills_category"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_companies_normalized_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_domain"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
