"""Vector schema: resumes, chunks, job embeddings, cached match scores

pgvector is used for *retrieval*, never for scoring. Embedding a whole resume
and a whole job description and taking the cosine similarity yields roughly the
same number for every pair — the two are stylistically different documents, so
the measure does not discriminate between a great fit and a poor one, and it
produces a figure nobody can explain.

What vectors are good at here is finding which of your resume bullets evidence
a given requirement, which is what grounds the Phase 3 gap analysis in your
actual text rather than in a summary. Scoring itself is deterministic and
auditable; see app/services/matching.py.
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.db.rls import disable_user_isolation, enable_user_isolation, grant_shared_table

revision: str = "0003_vector_schema"
down_revision: str | None = "0002_tracker_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resumes",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("parsed_text", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_resumes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
    )
    op.create_index(op.f("ix_resumes_user_id"), "resumes", ["user_id"], unique=False)
    op.create_table(
        "job_embeddings",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_embeddings_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_embeddings")),
        sa.UniqueConstraint("job_id", "ordinal", name="uq_job_embeddings_job_ordinal"),
    )
    op.create_index(op.f("ix_job_embeddings_job_id"), "job_embeddings", ["job_id"], unique=False)
    op.create_table(
        "match_analyses",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column(
            "subscores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "matched_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "missing_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "strengths",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "gaps", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=40), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_match_analyses_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_match_analyses_resume_id_resumes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_match_analyses_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_analyses")),
        sa.UniqueConstraint("resume_id", "job_id", name="uq_match_analyses_resume_job"),
    )
    op.create_index(op.f("ix_match_analyses_job_id"), "match_analyses", ["job_id"], unique=False)
    op.create_index(op.f("ix_match_analyses_user_id"), "match_analyses", ["user_id"], unique=False)
    op.create_table(
        "resume_chunks",
        sa.Column("resume_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=60), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
            name=op.f("fk_resume_chunks_resume_id_resumes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_resume_chunks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resume_chunks")),
    )
    op.create_index(
        "ix_resume_chunks_resume_ordinal", "resume_chunks", ["resume_id", "ordinal"], unique=False
    )
    op.create_index(op.f("ix_resume_chunks_user_id"), "resume_chunks", ["user_id"], unique=False)
    op.drop_constraint(
        op.f("ck_application_events_event_type_valid"), "application_events", type_="check"
    )
    op.drop_constraint(
        op.f("ck_application_events_source_valid"), "application_events", type_="check"
    )
    op.drop_constraint(op.f("ck_applications_current_status_valid"), "applications", type_="check")
    op.drop_constraint(op.f("ck_applications_priority_valid"), "applications", type_="check")
    op.drop_constraint(op.f("ck_interview_stages_outcome_valid"), "interview_stages", type_="check")
    op.drop_constraint(
        op.f("ck_interview_stages_round_number_positive"), "interview_stages", type_="check"
    )
    op.drop_constraint(
        op.f("ck_interview_stages_stage_type_valid"), "interview_stages", type_="check"
    )
    op.drop_constraint(op.f("ck_job_requirements_kind_valid"), "job_requirements", type_="check")
    op.create_unique_constraint(
        "uq_job_skills_job_id_skill_id", "job_skills", ["job_id", "skill_id"]
    )
    op.drop_constraint(op.f("ck_jobs_employment_type_valid"), "jobs", type_="check")
    op.drop_constraint(op.f("ck_jobs_salary_period_valid"), "jobs", type_="check")
    op.drop_constraint(op.f("ck_jobs_salary_range_ordered"), "jobs", type_="check")
    op.drop_constraint(op.f("ck_jobs_seniority_valid"), "jobs", type_="check")
    op.drop_constraint(op.f("ck_jobs_work_mode_valid"), "jobs", type_="check")
    op.drop_constraint(op.f("ck_jobs_years_range_ordered"), "jobs", type_="check")
    # ### end Alembic commands ###

    # Tenant-scoped: a resume is the most personal document in the system.
    for table in ("resumes", "resume_chunks", "match_analyses"):
        for statement in enable_user_isolation(table):
            op.execute(statement)

    # job_embeddings follows `jobs` — shared, since a job description is public.
    for statement in grant_shared_table("job_embeddings"):
        op.execute(statement)

    # HNSW rather than IVFFlat: IVFFlat needs training data to build its lists,
    # so it is useless on an empty table and would have to be rebuilt once rows
    # accumulate. HNSW is good immediately and stays good as rows are added,
    # which suits a corpus that grows one job at a time.
    #
    # vector_cosine_ops because bge embeddings are normalised for cosine.
    op.execute(
        "CREATE INDEX ix_vec_resume_chunks_embedding ON resume_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_vec_job_embeddings_embedding ON job_embeddings "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_vec_job_embeddings_embedding")
    op.execute("DROP INDEX IF EXISTS ix_vec_resume_chunks_embedding")
    for statement in disable_user_isolation("match_analyses"):
        op.execute(statement)
    for statement in disable_user_isolation("resume_chunks"):
        op.execute(statement)
    for statement in disable_user_isolation("resumes"):
        op.execute(statement)
    op.execute("REVOKE ALL ON job_embeddings FROM app_user")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_jobs_years_range_ordered"),
        "jobs",
        "years_experience_min IS NULL OR years_experience_max IS NULL OR years_experience_min <= years_experience_max",
    )
    op.create_check_constraint(
        op.f("ck_jobs_work_mode_valid"),
        "jobs",
        "work_mode IS NULL OR (work_mode::text = ANY (ARRAY['onsite'::character varying, 'hybrid'::character varying, 'remote'::character varying]::text[]))",
    )
    op.create_check_constraint(
        op.f("ck_jobs_seniority_valid"),
        "jobs",
        "seniority IS NULL OR (seniority::text = ANY (ARRAY['intern'::character varying, 'junior'::character varying, 'mid'::character varying, 'senior'::character varying, 'staff'::character varying, 'principal'::character varying, 'lead'::character varying]::text[]))",
    )
    op.create_check_constraint(
        op.f("ck_jobs_salary_range_ordered"),
        "jobs",
        "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
    )
    op.create_check_constraint(
        op.f("ck_jobs_salary_period_valid"),
        "jobs",
        "salary_period IS NULL OR (salary_period::text = ANY (ARRAY['year'::character varying, 'month'::character varying, 'hour'::character varying]::text[]))",
    )
    op.create_check_constraint(
        op.f("ck_jobs_employment_type_valid"),
        "jobs",
        "employment_type IS NULL OR (employment_type::text = ANY (ARRAY['full_time'::character varying, 'part_time'::character varying, 'contract'::character varying, 'internship'::character varying]::text[]))",
    )
    op.drop_constraint("uq_job_skills_job_id_skill_id", "job_skills", type_="unique")
    op.create_check_constraint(
        op.f("ck_job_requirements_kind_valid"),
        "job_requirements",
        "kind::text = ANY (ARRAY['must'::character varying, 'nice'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_interview_stages_stage_type_valid"),
        "interview_stages",
        "stage_type::text = ANY (ARRAY['hr_screen'::character varying, 'recruiter_call'::character varying, 'technical'::character varying, 'coding'::character varying, 'system_design'::character varying, 'managerial'::character varying, 'hiring_manager'::character varying, 'culture_fit'::character varying, 'take_home'::character varying, 'final'::character varying, 'other'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_interview_stages_round_number_positive"), "interview_stages", "round_number >= 1"
    )
    op.create_check_constraint(
        op.f("ck_interview_stages_outcome_valid"),
        "interview_stages",
        "outcome::text = ANY (ARRAY['pending'::character varying, 'passed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_applications_priority_valid"),
        "applications",
        "priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_applications_current_status_valid"),
        "applications",
        "current_status::text = ANY (ARRAY['saved'::character varying, 'applied'::character varying, 'screening'::character varying, 'interviewing'::character varying, 'offer'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'withdrawn'::character varying, 'ghosted'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_application_events_source_valid"),
        "application_events",
        "source::text = ANY (ARRAY['manual'::character varying, 'agent'::character varying, 'system'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_application_events_event_type_valid"),
        "application_events",
        "event_type::text = ANY (ARRAY['saved'::character varying, 'applied'::character varying, 'assessment_received'::character varying, 'screening_scheduled'::character varying, 'screening_done'::character varying, 'interview_scheduled'::character varying, 'interview_done'::character varying, 'offer_received'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'withdrawn'::character varying, 'marked_ghosted'::character varying, 'recruiter_reply'::character varying, 'follow_up_sent'::character varying, 'note_added'::character varying]::text[])",
    )
    op.drop_index(op.f("ix_resume_chunks_user_id"), table_name="resume_chunks")
    op.drop_index("ix_resume_chunks_resume_ordinal", table_name="resume_chunks")
    op.drop_table("resume_chunks")
    op.drop_index(op.f("ix_match_analyses_user_id"), table_name="match_analyses")
    op.drop_index(op.f("ix_match_analyses_job_id"), table_name="match_analyses")
    op.drop_table("match_analyses")
    op.drop_index(op.f("ix_job_embeddings_job_id"), table_name="job_embeddings")
    op.drop_table("job_embeddings")
    op.drop_index(op.f("ix_resumes_user_id"), table_name="resumes")
    op.drop_table("resumes")
    # ### end Alembic commands ###
