"""Follow-up rules: when silence becomes worth acting on

Rules are rows rather than constants because the right interval is a personal
judgement that differs by stage — a week of quiet after applying is normal, a
week after a final interview is not.

They are evaluated by a SQL query, never by a model. "Seven days since the
screening" is a date subtraction; routing it through an LLM would make a
deterministic rule non-deterministic, spend tokens on every sweep, and remove
the ability to unit-test the one part of this feature that must not be wrong.
The model's job starts afterwards: explaining the situation and drafting the
message.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_user_isolation, enable_user_isolation
from app.domain.enums import ApplicationStatus, FollowUpAction, check_constraint

revision: str = "0005_follow_up_rules"
down_revision: str | None = "0004_shared_table_policies"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow_up_rules",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("applies_to_status", sa.String(length=20), nullable=False),
        sa.Column("days_threshold", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_follow_up_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_up_rules")),
        sa.UniqueConstraint(
            "user_id", "applies_to_status", "action", name="uq_follow_up_rules_user_status_action"
        ),
    )
    op.create_index(
        op.f("ix_follow_up_rules_user_id"), "follow_up_rules", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        "applies_to_status_valid",
        "follow_up_rules",
        f"applies_to_status {check_constraint(ApplicationStatus)}",
    )
    op.create_check_constraint(
        "action_valid", "follow_up_rules", f"action {check_constraint(FollowUpAction)}"
    )
    # A zero-day rule would fire on every application the moment it was created,
    # and a year is well past the point of usefulness.
    op.create_check_constraint(
        "days_threshold_sane", "follow_up_rules", "days_threshold BETWEEN 1 AND 365"
    )

    for statement in enable_user_isolation("follow_up_rules"):
        op.execute(statement)


def downgrade() -> None:
    for statement in disable_user_isolation("follow_up_rules"):
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_follow_up_rules_user_id"), table_name="follow_up_rules")
    op.drop_table("follow_up_rules")
    # ### end Alembic commands ###
