"""Conversation memory for the assistant

Held server-side rather than in the browser so a thread survives a reload and
closing the drawer. Without it every message is independent, which is why
"what skills did it ask for" followed by "Setoo" lost the question entirely.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.rls import disable_user_isolation, enable_user_isolation
from app.domain.enums import MessageRole, check_constraint

revision: str = "0006_agent_messages"
down_revision: str | None = "0005_follow_up_rules"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_messages",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_agent_messages_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_messages")),
    )
    op.create_index(
        "ix_agent_messages_user_created", "agent_messages", ["user_id", "created_at"], unique=False
    )
    op.drop_constraint(op.f("ck_follow_up_rules_action_valid"), "follow_up_rules", type_="check")
    op.drop_constraint(
        op.f("ck_follow_up_rules_applies_to_status_valid"), "follow_up_rules", type_="check"
    )
    op.drop_constraint(
        op.f("ck_follow_up_rules_days_threshold_sane"), "follow_up_rules", type_="check"
    )
    # ### end Alembic commands ###

    op.create_check_constraint(
        "role_valid", "agent_messages", f"role {check_constraint(MessageRole)}"
    )

    # A conversation is as personal as the applications it discusses.
    for statement in enable_user_isolation("agent_messages"):
        op.execute(statement)


def downgrade() -> None:
    for statement in disable_user_isolation("agent_messages"):
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_follow_up_rules_days_threshold_sane"),
        "follow_up_rules",
        "days_threshold >= 1 AND days_threshold <= 365",
    )
    op.create_check_constraint(
        op.f("ck_follow_up_rules_applies_to_status_valid"),
        "follow_up_rules",
        "applies_to_status::text = ANY (ARRAY['saved'::character varying, 'applied'::character varying, 'screening'::character varying, 'interviewing'::character varying, 'offer'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'withdrawn'::character varying, 'ghosted'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_follow_up_rules_action_valid"),
        "follow_up_rules",
        "action::text = ANY (ARRAY['suggest_followup'::character varying, 'mark_ghosted'::character varying]::text[])",
    )
    op.drop_index("ix_agent_messages_user_created", table_name="agent_messages")
    op.drop_table("agent_messages")
    # ### end Alembic commands ###
